### PR TITLE
AMP Review 2

### PR DESCRIPTION
**Pull request by andrewrreed**
# Purpose

The purpose of this PR is provide an collaboration space to facilitate the Final Review of **AMP_4 NeuralQA**.

### CODE REVIEW

**Comment by andrewrreed** [comment]
https://github.com/andrewrreed/cml_neuralqa/blob/fc6d58160034d2a1b3b21a5b46316fe674864460/.project-metadata.yaml#L3

testing

**Comment by andrewrreed** [comment]
testing permalink from repo master:

https://github.com/andrewrreed/cml_neuralqa/blob/fc6d58160034d2a1b3b21a5b46316fe674864460/.project-metadata.yaml#L1-L7

**Comment by andrewrreed** [comment]
test 2:

https://github.com/fastforwardlabs/cml_neuralqa/blob/224d6f1e8c5800c61363a6cba3e6629f5f7500d5/.project-metadata.yaml#L1-L7

**Comment by andrewrreed** [comment]
@cjwallace FYI - ^^ looks like the permalinks only render properly if the code they link to is from the current repo - meaning, any code callouts need to be from the `fastforwardlabs/master` not `andrewrreed/master`

**Comment by cjwallace** [comment]
In general, I have little to point to in the code, this is a pretty easy pass.

One comment. [launch.py](https://github.com/fastforwardlabs/cml_neuralqa/blob/master/launch.py) uses mostly undocumented private APIs via the cmlbootstrap library. It's my understanding that we want to stay away from this, since it isn't supported. If that understanding is correct we should ditch this method of setup.

**Comment by andrewrreed** [comment]
@alexbleakley Can you confirm that Chris's understanding is correct? If so, I'll remove that method of setup from this AMP, and moving forward, enforce that the `cmlbootstrap` library should be avoided (unless its absolutely necessary - like in the Churn AMP to set environment variables)

**Comment by andrewrreed** [comment]
@cjwallace I agree with your assessment that we should not encourage the use of CMLBootstrap. I've removed the `launch.py` script and the associated discussion about it in the `README.md`. Once the officially supported CML API is available we can refactor to include it (and will probably need to do the same for other AMPs as well). For now, I'm going to go ahead and merge these changes and call this AMP complete.

@alexbleakley FYI ^

**Comment by alexbleakley** [comment]
@andrewrreed Yes, that is precisely the preferred approach. Thanks!

**Pull request merged**
